//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripBliss.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TripBliss.Resources.Language.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Request.
        /// </summary>
        internal static string btnAddRequest {
            get {
                return ResourceManager.GetString("btnAddRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string btnApply_Forgot {
            get {
                return ResourceManager.GetString("btnApply-Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributors.
        /// </summary>
        internal static string btnDistributors {
            get {
                return ResourceManager.GetString("btnDistributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites.
        /// </summary>
        internal static string btnFavourites {
            get {
                return ResourceManager.GetString("btnFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string btnHome {
            get {
                return ResourceManager.GetString("btnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG IN.
        /// </summary>
        internal static string btnLogIn_Login {
            get {
                return ResourceManager.GetString("btnLogIn-Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency.
        /// </summary>
        internal static string hdrAgency {
            get {
                return ResourceManager.GetString("hdrAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Distributor.
        /// </summary>
        internal static string hdrChooseDistributor {
            get {
                return ResourceManager.GetString("hdrChooseDistributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributors.
        /// </summary>
        internal static string hdrDistributors {
            get {
                return ResourceManager.GetString("hdrDistributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string hdrHistory {
            get {
                return ResourceManager.GetString("hdrHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string hdrMore {
            get {
                return ResourceManager.GetString("hdrMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Requests.
        /// </summary>
        internal static string hdrMyRequests {
            get {
                return ResourceManager.GetString("hdrMyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Request.
        /// </summary>
        internal static string hdrNewRequest {
            get {
                return ResourceManager.GetString("hdrNewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        internal static string hdrOffers {
            get {
                return ResourceManager.GetString("hdrOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string lblAccount_More {
            get {
                return ResourceManager.GetString("lblAccount-More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult.
        /// </summary>
        internal static string lblAdult_AirService {
            get {
                return ResourceManager.GetString("lblAdult-AirService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Flight Services.
        /// </summary>
        internal static string lblAirFlightServices {
            get {
                return ResourceManager.GetString("lblAirFlightServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string lblBrand_TranServices {
            get {
                return ResourceManager.GetString("lblBrand-TranServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier.
        /// </summary>
        internal static string lblCarrier_AirService {
            get {
                return ResourceManager.GetString("lblCarrier-AirService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Type.
        /// </summary>
        internal static string lblCarType_TranService {
            get {
                return ResourceManager.GetString("lblCarType-TranService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        internal static string lblCheckIn_HotelService {
            get {
                return ResourceManager.GetString("lblCheckIn-HotelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        internal static string lblCheckOut_HotelService {
            get {
                return ResourceManager.GetString("lblCheckOut-HotelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        internal static string lblChild_AirService {
            get {
                return ResourceManager.GetString("lblChild-AirService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string lblClass_AirService {
            get {
                return ResourceManager.GetString("lblClass-AirService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string lblDate_TranService {
            get {
                return ResourceManager.GetString("lblDate-TranService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an Account? .
        /// </summary>
        internal static string lblDHAccount_Login {
            get {
                return ResourceManager.GetString("lblDHAccount-Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discription.
        /// </summary>
        internal static string lblDiscription_OfferDetails {
            get {
                return ResourceManager.GetString("lblDiscription-OfferDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETA.
        /// </summary>
        internal static string lblETA_AirService {
            get {
                return ResourceManager.GetString("lblETA-AirService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETD.
        /// </summary>
        internal static string lblETD_AirService {
            get {
                return ResourceManager.GetString("lblETD-AirService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string lblExit_More {
            get {
                return ResourceManager.GetString("lblExit-More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string lblFavorites_More {
            get {
                return ResourceManager.GetString("lblFavorites-More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string lblForgotPassword_Login {
            get {
                return ResourceManager.GetString("lblForgotPassword-Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string lblFrom_TranService {
            get {
                return ResourceManager.GetString("lblFrom-TranService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve got an account already?.
        /// </summary>
        internal static string lblHaveAccount_SignUp {
            get {
                return ResourceManager.GetString("lblHaveAccount-SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Name.
        /// </summary>
        internal static string lblHotelName_HotelService {
            get {
                return ResourceManager.GetString("lblHotelName-HotelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Services.
        /// </summary>
        internal static string lblHotelServices {
            get {
                return ResourceManager.GetString("lblHotelServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infant.
        /// </summary>
        internal static string lblInfant_AirService {
            get {
                return ResourceManager.GetString("lblInfant-AirService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string lblLanguage_More {
            get {
                return ResourceManager.GetString("lblLanguage-More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meals.
        /// </summary>
        internal static string lblMeals_HotelService {
            get {
                return ResourceManager.GetString("lblMeals-HotelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string lblModel_TranService {
            get {
                return ResourceManager.GetString("lblModel-TranService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Of Room.
        /// </summary>
        internal static string lblNoOfRoom_HotelService {
            get {
                return ResourceManager.GetString("lblNoOfRoom-HotelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No .s.
        /// </summary>
        internal static string lblNos_TranService {
            get {
                return ResourceManager.GetString("lblNos-TranService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string lblNotes_HotelService {
            get {
                return ResourceManager.GetString("lblNotes-HotelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass No..
        /// </summary>
        internal static string lblPassNo_VisaService {
            get {
                return ResourceManager.GetString("lblPassNo-VisaService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string lblPrivacyPolicy_More {
            get {
                return ResourceManager.GetString("lblPrivacyPolicy-More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Type.
        /// </summary>
        internal static string lblRoomType_HotelService {
            get {
                return ResourceManager.GetString("lblRoomType-HotelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room View.
        /// </summary>
        internal static string lblRoomView_HotelService {
            get {
                return ResourceManager.GetString("lblRoomView-HotelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string lblSelectAll_ActiveDistributors {
            get {
                return ResourceManager.GetString("lblSelectAll-ActiveDistributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string lblSignIn_SignUp {
            get {
                return ResourceManager.GetString("lblSignIn-SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string lblSignUp_Login {
            get {
                return ResourceManager.GetString("lblSignUp-Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string lblSupport_More {
            get {
                return ResourceManager.GetString("lblSupport-More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms&amp;Conditions.
        /// </summary>
        internal static string lblTermesConditions_More {
            get {
                return ResourceManager.GetString("lblTermesConditions-More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string lblTime_TranService {
            get {
                return ResourceManager.GetString("lblTime-TranService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string lblTo_TranService {
            get {
                return ResourceManager.GetString("lblTo-TranService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation Services.
        /// </summary>
        internal static string lblTransportationServices {
            get {
                return ResourceManager.GetString("lblTransportationServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string lblUsers_More {
            get {
                return ResourceManager.GetString("lblUsers-More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Services.
        /// </summary>
        internal static string lblVisaServices {
            get {
                return ResourceManager.GetString("lblVisaServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Type.
        /// </summary>
        internal static string lblVisaType_VisaService {
            get {
                return ResourceManager.GetString("lblVisaType-VisaService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string plcCompanyName_SignUp {
            get {
                return ResourceManager.GetString("plcCompanyName-SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Phone.
        /// </summary>
        internal static string plcCompanyPhone_SignUp {
            get {
                return ResourceManager.GetString("plcCompanyPhone-SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string plcConfirmPassword_SignUp {
            get {
                return ResourceManager.GetString("plcConfirmPassword-SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string plcEmail_Login {
            get {
                return ResourceManager.GetString("plcEmail-Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string plcPassword_Lohin {
            get {
                return ResourceManager.GetString("plcPassword-Lohin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string plcSearch {
            get {
                return ResourceManager.GetString("plcSearch", resourceCulture);
            }
        }
    }
}
