//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripBliss.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TripBliss.Resources.Language.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active details.
        /// </summary>
        internal static string ActiveDetails___HotelServices {
            get {
                return ResourceManager.GetString("ActiveDetails - HotelServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Distributors.
        /// </summary>
        internal static string btnActiveDistributors_RequestDetails {
            get {
                return ResourceManager.GetString("btnActiveDistributors-RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Request.
        /// </summary>
        internal static string btnAddRequest {
            get {
                return ResourceManager.GetString("btnAddRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string btnApply_Forgot {
            get {
                return ResourceManager.GetString("btnApply-Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        internal static string btnattachment_VisaDetails {
            get {
                return ResourceManager.GetString("btnattachment-VisaDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancle_PopupLan {
            get {
                return ResourceManager.GetString("btnCancle-PopupLan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string btnConfirm_NewRequest {
            get {
                return ResourceManager.GetString("btnConfirm-NewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        internal static string btnDeleteAll_AttatchmentPage {
            get {
                return ResourceManager.GetString("btnDeleteAll-AttatchmentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributors.
        /// </summary>
        internal static string btnDistributors {
            get {
                return ResourceManager.GetString("btnDistributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites.
        /// </summary>
        internal static string btnFavourites {
            get {
                return ResourceManager.GetString("btnFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string btnHome {
            get {
                return ResourceManager.GetString("btnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG IN.
        /// </summary>
        internal static string btnLogIn_Login {
            get {
                return ResourceManager.GetString("btnLogIn-Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string btnPayNow_NewRequest {
            get {
                return ResourceManager.GetString("btnPayNow-NewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Photo from Gallery.
        /// </summary>
        internal static string btnPickPhoto_attatchmentPopup {
            get {
                return ResourceManager.GetString("btnPickPhoto-attatchmentPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Details.
        /// </summary>
        internal static string btnRequestDetails_RequestDetails {
            get {
                return ResourceManager.GetString("btnRequestDetails-RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        internal static string btnResponse_RequestDetails {
            get {
                return ResourceManager.GetString("btnResponse-RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Photo.
        /// </summary>
        internal static string btnTakePhoto_attatchmentPopup {
            get {
                return ResourceManager.GetString("btnTakePhoto-attatchmentPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Number.
        /// </summary>
        internal static string DriverNumber_TransportActive {
            get {
                return ResourceManager.GetString("DriverNumber-TransportActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Payment.
        /// </summary>
        internal static string FullPayment_payment {
            get {
                return ResourceManager.GetString("FullPayment-payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Name.
        /// </summary>
        internal static string GuestId_HotelActive {
            get {
                return ResourceManager.GetString("GuestId-HotelActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Guest.
        /// </summary>
        internal static string hdAddGuest {
            get {
                return ResourceManager.GetString("hdAddGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Flight Details.
        /// </summary>
        internal static string hdAirFlightDetails {
            get {
                return ResourceManager.GetString("hdAirFlightDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Response.
        /// </summary>
        internal static string hdConfirmResponse {
            get {
                return ResourceManager.GetString("hdConfirmResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Details.
        /// </summary>
        internal static string hdHotelDetails {
            get {
                return ResourceManager.GetString("hdHotelDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Photo.
        /// </summary>
        internal static string hdrAddPhoto_attachmentPopup {
            get {
                return ResourceManager.GetString("hdrAddPhoto-attachmentPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency.
        /// </summary>
        internal static string hdrAgency {
            get {
                return ResourceManager.GetString("hdrAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Flight Attachment.
        /// </summary>
        internal static string hdrAirFlightAttachment {
            get {
                return ResourceManager.GetString("hdrAirFlightAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Distributor.
        /// </summary>
        internal static string hdrChooseDistributor {
            get {
                return ResourceManager.GetString("hdrChooseDistributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Offer.
        /// </summary>
        internal static string hdrCreateOffer_CreateOffer {
            get {
                return ResourceManager.GetString("hdrCreateOffer-CreateOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributors.
        /// </summary>
        internal static string hdrDistributors {
            get {
                return ResourceManager.GetString("hdrDistributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string hdrHistory {
            get {
                return ResourceManager.GetString("hdrHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string hdrMore {
            get {
                return ResourceManager.GetString("hdrMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Requests.
        /// </summary>
        internal static string hdrMyRequests {
            get {
                return ResourceManager.GetString("hdrMyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Request.
        /// </summary>
        internal static string hdrNewRequest {
            get {
                return ResourceManager.GetString("hdrNewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        internal static string hdrOffers {
            get {
                return ResourceManager.GetString("hdrOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string hdrSelectLan_PopupLan {
            get {
                return ResourceManager.GetString("hdrSelectLan-PopupLan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        internal static string hdrvehicle_RequestDetails {
            get {
                return ResourceManager.GetString("hdrvehicle-RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewers.
        /// </summary>
        internal static string hdrViewers_OfferViewers {
            get {
                return ResourceManager.GetString("hdrViewers-OfferViewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Attachment.
        /// </summary>
        internal static string hdrVisaAttachment {
            get {
                return ResourceManager.GetString("hdrVisaAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportaion Details.
        /// </summary>
        internal static string hdTransportaionDetails {
            get {
                return ResourceManager.GetString("hdTransportaionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Details.
        /// </summary>
        internal static string hdVisaDetails {
            get {
                return ResourceManager.GetString("hdVisaDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string lblAccount_More {
            get {
                return ResourceManager.GetString("lblAccount-More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string lblActive_HomeDist {
            get {
                return ResourceManager.GetString("lblActive-HomeDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult.
        /// </summary>
        internal static string lblAdult_AirService {
            get {
                return ResourceManager.GetString("lblAdult-AirService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Flight Services.
        /// </summary>
        internal static string lblAirFlightServices {
            get {
                return ResourceManager.GetString("lblAirFlightServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string lblAll_HomeDist {
            get {
                return ResourceManager.GetString("lblAll-HomeDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string lblBrand_TranServices {
            get {
                return ResourceManager.GetString("lblBrand-TranServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier.
        /// </summary>
        internal static string lblCarrier_AirService {
            get {
                return ResourceManager.GetString("lblCarrier-AirService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Type.
        /// </summary>
        internal static string lblCarType_TranService {
            get {
                return ResourceManager.GetString("lblCarType-TranService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        internal static string lblCheckIn_HotelService {
            get {
                return ResourceManager.GetString("lblCheckIn-HotelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        internal static string lblCheckOut_HotelService {
            get {
                return ResourceManager.GetString("lblCheckOut-HotelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        internal static string lblChild_AirService {
            get {
                return ResourceManager.GetString("lblChild-AirService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string lblClass_AirService {
            get {
                return ResourceManager.GetString("lblClass-AirService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string lblDate_TranService {
            get {
                return ResourceManager.GetString("lblDate-TranService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an Account? .
        /// </summary>
        internal static string lblDHAccount_Login {
            get {
                return ResourceManager.GetString("lblDHAccount-Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discription.
        /// </summary>
        internal static string lblDiscription_OfferDetails {
            get {
                return ResourceManager.GetString("lblDiscription-OfferDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string lblDocuments_MorePage {
            get {
                return ResourceManager.GetString("lblDocuments-MorePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETA.
        /// </summary>
        internal static string lblETA_AirService {
            get {
                return ResourceManager.GetString("lblETA-AirService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETD.
        /// </summary>
        internal static string lblETD_AirService {
            get {
                return ResourceManager.GetString("lblETD-AirService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string lblExit_More {
            get {
                return ResourceManager.GetString("lblExit-More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string lblFavorites_More {
            get {
                return ResourceManager.GetString("lblFavorites-More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string lblForgotPassword_Login {
            get {
                return ResourceManager.GetString("lblForgotPassword-Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string lblFrom_TranService {
            get {
                return ResourceManager.GetString("lblFrom-TranService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve got an account already?.
        /// </summary>
        internal static string lblHaveAccount_SignUp {
            get {
                return ResourceManager.GetString("lblHaveAccount-SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Name.
        /// </summary>
        internal static string lblHotelName_HotelService {
            get {
                return ResourceManager.GetString("lblHotelName-HotelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Services.
        /// </summary>
        internal static string lblHotelServices {
            get {
                return ResourceManager.GetString("lblHotelServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string lblImage_CreateOffer {
            get {
                return ResourceManager.GetString("lblImage-CreateOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infant.
        /// </summary>
        internal static string lblInfant_AirService {
            get {
                return ResourceManager.GetString("lblInfant-AirService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsDriver.
        /// </summary>
        internal static string lblIsDriver_RequestDetails {
            get {
                return ResourceManager.GetString("lblIsDriver-RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string lblLanguage_More {
            get {
                return ResourceManager.GetString("lblLanguage-More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string lblLocation_HotelSevice {
            get {
                return ResourceManager.GetString("lblLocation-HotelSevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meals.
        /// </summary>
        internal static string lblMeals_HotelService {
            get {
                return ResourceManager.GetString("lblMeals-HotelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string lblModel_TranService {
            get {
                return ResourceManager.GetString("lblModel-TranService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string lblModelName_RequestDetails {
            get {
                return ResourceManager.GetString("lblModelName-RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Rate per Day.
        /// </summary>
        internal static string lblMRPD_RequestDetails {
            get {
                return ResourceManager.GetString("lblMRPD-RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nights.
        /// </summary>
        internal static string lblNights_RequestDetails {
            get {
                return ResourceManager.GetString("lblNights-RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string lblNo_RequestDetails {
            get {
                return ResourceManager.GetString("lblNo-RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Of Room.
        /// </summary>
        internal static string lblNoOfRoom_HotelService {
            get {
                return ResourceManager.GetString("lblNoOfRoom-HotelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No .s.
        /// </summary>
        internal static string lblNos_TranService {
            get {
                return ResourceManager.GetString("lblNos-TranService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Active.
        /// </summary>
        internal static string lblNotActive_HomeDist {
            get {
                return ResourceManager.GetString("lblNotActive-HomeDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note For Agency.
        /// </summary>
        internal static string lblNoteForAgency_HotelService {
            get {
                return ResourceManager.GetString("lblNoteForAgency-HotelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note For Distributor.
        /// </summary>
        internal static string lblNoteForDist_HotelService {
            get {
                return ResourceManager.GetString("lblNoteForDist-HotelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string lblNotes_HotelService {
            get {
                return ResourceManager.GetString("lblNotes-HotelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Plan.
        /// </summary>
        internal static string lblOfferPlan_CreateOffer {
            get {
                return ResourceManager.GetString("lblOfferPlan-CreateOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer URL.
        /// </summary>
        internal static string lblOfferUrl_CreateOffer {
            get {
                return ResourceManager.GetString("lblOfferUrl-CreateOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass No..
        /// </summary>
        internal static string lblPassNo_VisaService {
            get {
                return ResourceManager.GetString("lblPassNo-VisaService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string lblPrice_RequestDetails {
            get {
                return ResourceManager.GetString("lblPrice-RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string lblPrivacyPolicy_More {
            get {
                return ResourceManager.GetString("lblPrivacyPolicy-More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Basis.
        /// </summary>
        internal static string lblRateBasis_RequestDetails {
            get {
                return ResourceManager.GetString("lblRateBasis-RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Per Room.
        /// </summary>
        internal static string lblRatePR_RequestDetails_RequestDetails {
            get {
                return ResourceManager.GetString("lblRatePR-RequestDetails-RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Details.
        /// </summary>
        internal static string lblRoomDetails_RequestDetails {
            get {
                return ResourceManager.GetString("lblRoomDetails-RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Type.
        /// </summary>
        internal static string lblRoomType_HotelService {
            get {
                return ResourceManager.GetString("lblRoomType-HotelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room View.
        /// </summary>
        internal static string lblRoomView_HotelService {
            get {
                return ResourceManager.GetString("lblRoomView-HotelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string lblSelectAll_ActiveDistributors {
            get {
                return ResourceManager.GetString("lblSelectAll-ActiveDistributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string lblSignIn_SignUp {
            get {
                return ResourceManager.GetString("lblSignIn-SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string lblSignUp_Login {
            get {
                return ResourceManager.GetString("lblSignUp-Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string lblSupport_More {
            get {
                return ResourceManager.GetString("lblSupport-More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms&amp;Conditions.
        /// </summary>
        internal static string lblTermesConditions_More {
            get {
                return ResourceManager.GetString("lblTermesConditions-More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string lblTime_TranService {
            get {
                return ResourceManager.GetString("lblTime-TranService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        internal static string lblTitel_CreateOffer {
            get {
                return ResourceManager.GetString("lblTitel-CreateOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string lblTo_TranService {
            get {
                return ResourceManager.GetString("lblTo-TranService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation Services.
        /// </summary>
        internal static string lblTransportationServices {
            get {
                return ResourceManager.GetString("lblTransportationServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string lblTypeName_RequestDetails {
            get {
                return ResourceManager.GetString("lblTypeName-RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string lblUsers_More {
            get {
                return ResourceManager.GetString("lblUsers-More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video URL.
        /// </summary>
        internal static string lblVideoUrl_CreateOffer {
            get {
                return ResourceManager.GetString("lblVideoUrl-CreateOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string lblView_RequestDetails {
            get {
                return ResourceManager.GetString("lblView-RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Services.
        /// </summary>
        internal static string lblVisaServices {
            get {
                return ResourceManager.GetString("lblVisaServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Type.
        /// </summary>
        internal static string lblVisaType_VisaService {
            get {
                return ResourceManager.GetString("lblVisaType-VisaService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutStanding Balance.
        /// </summary>
        internal static string OSBlance_payment {
            get {
                return ResourceManager.GetString("OSBlance-payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Company Type.
        /// </summary>
        internal static string pickerTitleCompanyType_SignUpPage {
            get {
                return ResourceManager.GetString("pickerTitleCompanyType-SignUpPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Number.
        /// </summary>
        internal static string PlateNumber_TransportActive {
            get {
                return ResourceManager.GetString("PlateNumber-TransportActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Email.
        /// </summary>
        internal static string plcCompanyEmail_SignUpPage {
            get {
                return ResourceManager.GetString("plcCompanyEmail-SignUpPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string plcCompanyName_SignUp {
            get {
                return ResourceManager.GetString("plcCompanyName-SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Phone.
        /// </summary>
        internal static string plcCompanyPhone_SignUp {
            get {
                return ResourceManager.GetString("plcCompanyPhone-SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string plcEmail_SignUpPage {
            get {
                return ResourceManager.GetString("plcEmail-SignUpPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string plcPassword_Login {
            get {
                return ResourceManager.GetString("plcPassword-Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string plcSearch {
            get {
                return ResourceManager.GetString("plcSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string plcUserName_Login {
            get {
                return ResourceManager.GetString("plcUserName-Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Reference Number.
        /// </summary>
        internal static string RoomRef_HotelActive {
            get {
                return ResourceManager.GetString("RoomRef-HotelActive", resourceCulture);
            }
        }
    }
}
